spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      exclude: "WEB-INF/**,META-INF/**,resources/**,static/**,public/**,templates/**"
      enabled: true
      additional-paths: "src/main/java,src/main/resources"
      trigger-file: ".trigger"
mybatis:
  configuration:
    map-underscore-to-camel-case: true
